
'use server';

import { generateRecipesFromIngredients } from '@/ai/flows/generate-recipes-from-ingredients';
import { PlaceHolderImages } from '@/lib/placeholder-images';
import type { Recipe } from '@/lib/types';
import { z } from 'zod';

const schema = z.object({
  ingredients: z.string().min(3, 'Please enter some ingredients.'),
});

export type FormState = {
  message: string;
  recipes?: Recipe[];
  error?: boolean;
};

function parseRecipes(rawRecipes: string): Recipe[] {
    if (!rawRecipes) return [];
  
    return rawRecipes.split('\n')
      .filter(r => r.trim() !== '')
      .map((r, index) => {
        const placeholder = PlaceHolderImages[index % PlaceHolderImages.length] || PlaceHolderImages[0];
        return {
          title: r.trim().replace(/^\d+\.\s*/, ''),
          description: `A delicious recipe generated by FridgeChef AI, perfect for using up your ingredients.`,
          image: placeholder.imageUrl,
          imageHint: placeholder.imageHint,
        };
      });
  }

export async function getRecipesAction(
  prevState: FormState,
  formData: FormData
): Promise<FormState> {
  const validatedFields = schema.safeParse({
    ingredients: formData.get('ingredients'),
  });

  if (!validatedFields.success) {
    return {
      message: 'Please enter at least 3 characters for ingredients.',
      error: true,
    };
  }
  
  try {
    const result = await generateRecipesFromIngredients({
      ingredients: validatedFields.data.ingredients,
    });

    const recipes = parseRecipes(result.recipes);
    
    if (recipes.length === 0) {
      return { message: 'No recipes found for these ingredients. Try adding more or being more specific!' };
    }

    return { message: 'Recipes generated successfully!', recipes };
  } catch (e) {
    console.error(e);
    return { message: 'An error occurred while generating recipes. Please try again.', error: true };
  }
}
